.github/workflows/snyk.yml
Closes # 
- [ ✅] My pull request adheres to the code style of this project
- [ ✅] My code requires changes to the documentation
- [ ✅] I have updated the documentation as required
- [ ✅] All the tests have passed
=> Feat: update synk action

apps/nt-stylesheet/README.md, apps/nt-stylesheet/bin/init-tailwind.js, apps/nt-stylesheet/package.json
=> feat: change package name

.github/workflows/publish-nt-css.yml
Github action configuration: only publish new version on NPM when new realease is created
=> conf: only publish new version when release

.github/workflows/bump-version-publish-css.yml
Closes #
update folder bump version
-   [x] The dependencies in `package.json` are correct and necessary (no unused or missing package
=> feat: update folder bump version

.github/workflows/bump-version.yml, lint-staged.config.js, package.json
Closes #
- Bump version if it fail
- Run husky when npm install begin  
-   [x] The dependencies in `package.json` are correct and necessary (no unused or missing package
=> Feat: still bump version if it fail

.github/workflows/bump-version.yml
Closes #
- Update bum version
-   [x] The dependencies in `package.json` are correct and necessary (no unused or missing package
=> feat: update bum version

.github/workflows/bump-version.yml
Closes #
-   [x] The dependencies in `package.json` are correct and necessary (no unused or missing package
=> feat: bump version with directory

.github/workflows/publish-nt-css.yml
Closes #
- Update title and tag when release
=> style: update title and tag release

apps/nt-headless-ui/components/ui/badge/badge.spec.tsx, apps/nt-headless-ui/components/ui/badge/badge.stories.tsx, apps/nt-headless-ui/components/ui/badge/badge.tsx, apps/nt-headless-ui/package.json, apps/nt-headless-ui/vite.config.ts, apps/nt-stylesheet/package.json, apps/nt-stylesheet/pnpm-lock.yaml, apps/nt-stylesheet/themes/colors.ts
=> feat: add badge button

apps/nt-headless-ui/pnpm-lock.yaml, package.json
Closes #
- Update script to deploy .
=> Feat: deploy vercel

apps/nt-headless-ui/.storybook/main.ts, apps/nt-headless-ui/package.json, apps/nt-headless-ui/pnpm-lock.yaml, apps/nt-headless-ui/stories/colors/brand.mdx, apps/nt-headless-ui/stories/colors/brand/brand.mdx, apps/nt-headless-ui/stories/colors/brand/colors.json, apps/nt-headless-ui/stories/colors/shades-primary/shades-primary.mdx, package.json, pnpm-lock.yaml
Closes #
- Add colors brand and shade primary
=> Feat: add brand colors and Shade primary markdown

.cspell.json, .github/workflows/mega-linter.yml, .gitignore, .jscpd.json, .mega-linter.yml, cspell.json
=> feat: init mega linter

apps/nt-headless-ui/components/ui/checkbox/checkbox.spec.tsx, apps/nt-headless-ui/components/ui/checkbox/checkbox.stories.tsx, apps/nt-headless-ui/components/ui/checkbox/checkbox.tsx, apps/nt-headless-ui/package.json, apps/nt-headless-ui/pnpm-lock.yaml
Closes #
- Add checkbox component & unit test 
=> feat: add checkbox component

apps/nt-headless-ui/components/ui/input/input.spec.tsx, apps/nt-headless-ui/components/ui/input/input.stories.tsx, apps/nt-headless-ui/components/ui/input/input.tsx
Closes #
- Add input component and unitest
=> Feat: add input component

apps/nt-headless-ui/components/ui/alert/alert.spec.tsx, apps/nt-headless-ui/components/ui/alert/alert.stories.tsx, apps/nt-headless-ui/components/ui/alert/alert.tsx, apps/nt-headless-ui/pnpm-lock.yaml, package.json, pnpm-lock.yaml
Closes #
- Add alert component
=> feat: add alert component and unit test for it

apps/nt-headless-ui/components/ui/select/radix-select.tsx, apps/nt-headless-ui/components/ui/select/select.spec.tsx, apps/nt-headless-ui/components/ui/select/select.stories.tsx, apps/nt-headless-ui/components/ui/select/select.tsx, apps/nt-headless-ui/package.json, apps/nt-headless-ui/pnpm-lock.yaml
Closes #
- add select component
=> Feat: add select component

.github/workflows/pr-coverage.yml, apps/nt-headless-ui/components.json, apps/nt-headless-ui/components/ui/progress/progress.spec.tsx, apps/nt-headless-ui/components/ui/progress/progress.stories.tsx, apps/nt-headless-ui/components/ui/progress/progress.tsx, apps/nt-headless-ui/package.json, apps/nt-headless-ui/pnpm-lock.yaml, apps/nt-headless-ui/tailwind.config.ts, apps/nt-headless-ui/tsconfig.json, apps/nt-headless-ui/vite.config.ts, apps/nt-stylesheet/vite.config.ts, apps/nt-stylesheet/vitest.workspace.ts, package.json, pnpm-lock.yaml
Closes #
- Add progress component 
- Add Coverage for PR 
=> Feat: Add progress component and PR coverage

apps/nt-headless-ui/components/ui/button/button.spec.tsx, apps/nt-headless-ui/components/ui/button/button.stories.tsx, apps/nt-headless-ui/components/ui/button/button.tsx
Closes #
- Refactor button component
=> Feat: refactor components button

apps/nt-headless-ui/components/ui/switch/switch.spec.tsx, apps/nt-headless-ui/components/ui/switch/switch.stories.tsx, apps/nt-headless-ui/components/ui/switch/switch.tsx, apps/nt-headless-ui/package.json, apps/nt-headless-ui/pnpm-lock.yaml
=> feat: add switch

apps/nt-headless-ui/components/ui/upload-file/upload-file.spec.tsx, apps/nt-headless-ui/components/ui/upload-file/upload-file.stories.tsx, apps/nt-headless-ui/components/ui/upload-file/upload-file.tsx
Closes #
- Add component upload file
=> feat: upload file

apps/nt-headless-ui/components/ui/avatar/avatar.spec.tsx, apps/nt-headless-ui/components/ui/avatar/avatar.tsx
=> Feat: update avatar

apps/nt-headless-ui/components/radix/command.tsx, apps/nt-headless-ui/components/radix/popover.tsx, apps/nt-headless-ui/components/radix/separator.tsx, apps/nt-headless-ui/components/radix/sheet.tsx, apps/nt-headless-ui/components/ui/combobox/combobox.spec.tsx, apps/nt-headless-ui/components/ui/combobox/combobox.stories.tsx, apps/nt-headless-ui/components/ui/combobox/combobox.tsx, apps/nt-headless-ui/package.json, apps/nt-headless-ui/pnpm-lock.yaml, apps/nt-headless-ui/setup-test.ts, apps/nt-stylesheet/pnpm-lock.yaml, pnpm-lock.yaml
=> Feat: Add combobox component 

.github/workflows/publish-nt-headless-ui.yml, apps/nt-headless-ui/package.json, apps/nt-headless-ui/tailwind.config.ts, package.json
=> Fix: pulbish UI

apps/nt-headless-ui/components/radix/sidebar.tsx, apps/nt-headless-ui/components/ui/sidebar/components/sidebar-group.spec.tsx, apps/nt-headless-ui/components/ui/sidebar/components/sidebar-group.tsx, apps/nt-headless-ui/components/ui/sidebar/sidebar.spec.tsx, apps/nt-headless-ui/components/ui/sidebar/sidebar.stories.tsx, apps/nt-headless-ui/components/ui/sidebar/sidebar.tsx
=> feat: update sidebar

apps/nt-headless-ui/components/ui/progress/progress.spec.tsx, apps/nt-headless-ui/components/ui/progress/progress.tsx
Closes #
- Update progress bar
=> feat: add display text progress

.github/workflows/bump-version.yml, .github/workflows/check-vulnerabilities.yml, .github/workflows/code-check.yml, .github/workflows/pr-coverage.yml, .github/workflows/publish-nt-css.yml, .github/workflows/publish-nt-headless-ui.yml, .github/workflows/snyk.yml, apps/nt-stylesheet/package.json, package.json
=> feat: update using pnpm 10

.github/pull-request-template.md, apps/nt-headless-ui/tailwind.config.ts
=> feat: update pr template and ts-ignore

.gitignore, apps/nt-headless-ui/components/radix/avatar.tsx, apps/nt-headless-ui/components/ui/avatar/avatar.spec.tsx, apps/nt-headless-ui/components/ui/avatar/avatar.stories.tsx, apps/nt-headless-ui/components/ui/avatar/avatar.tsx, apps/nt-headless-ui/components/ui/sidebar/sidebar.stories.tsx, apps/nt-stylesheet/docs/avatar.md, apps/nt-stylesheet/docs/button.md, apps/nt-stylesheet/examples/avatar.html, apps/nt-stylesheet/examples/index.html, apps/nt-stylesheet/src/styles/_utilities.scss, apps/nt-stylesheet/src/styles/_variables.scss, apps/nt-stylesheet/src/styles/components/_nt-avatar.scss
Summary #
- Update avatar component with nt-stylesheet
- add style for avatar
=> feat: update avatar nt-stylesheet

apps/nt-stylesheet/project.json, apps/nt-stylesheet/vite.config.dev.ts, package.json, pnpm-lock.yaml
Summary
justify server-static target for nt-stylesheet
=> chore:  justify server-static target for nt-stylesheet

apps/nt-headless-ui/components/ui/alert/alert.spec.tsx, apps/nt-headless-ui/components/ui/alert/alert.stories.tsx, apps/nt-headless-ui/components/ui/alert/alert.tsx, apps/nt-headless-ui/components/ui/alert/index.ts
Summary #
- Apply alert component with nt-stylesheet
=> feat: apply alert with nt-stylesheet

apps/nt-headless-ui/components/ui/alert/alert.spec.tsx, apps/nt-headless-ui/components/ui/input/input.spec.tsx, apps/nt-headless-ui/components/ui/input/input.stories.tsx, apps/nt-headless-ui/components/ui/input/input.tsx
Summary #
- Apply Input component with nt-stylesheet
=> Feat: Input component with nt-stylesheet

apps/nt-headless-ui/components/radix/dialog.tsx, apps/nt-headless-ui/components/ui/modal/index.ts, apps/nt-headless-ui/components/ui/modal/modal.spec.tsx, apps/nt-headless-ui/components/ui/modal/modal.stories.tsx, apps/nt-headless-ui/components/ui/modal/modal.tsx, apps/nt-stylesheet/examples/index.html, apps/nt-stylesheet/src/styles/components/_nt-modal.scss
Summary #
- Add modal apply with nt-stylesheet
=> feat: add component modal apply with nt-stylesheet

apps/nt-stylesheet/examples/checkbox.html, apps/nt-stylesheet/examples/index.html, apps/nt-stylesheet/examples/scripts/main.js
Summary #
- Add main.js & update fix checkbox indeterminate
=> feat: add main.js and fix checkbox indeterminate

apps/nt-headless-ui/components/radix/popover.tsx, apps/nt-headless-ui/components/ui/popover/popover.spec.tsx, apps/nt-headless-ui/components/ui/popover/popover.stories.tsx, apps/nt-headless-ui/components/ui/popover/popover.tsx, apps/nt-stylesheet/src/styles/components/_nt-popover.scss
Summary #
- Update component tooltip with stylesheet
-   [x] The code is lintted with ESLint
=> feat: Update component tooltip with stylesheet

.github/workflows/publish-and-release-reusable.yml, .github/workflows/publish-libs-nt-headless-ui.yml, .github/workflows/publish-nt-stylesheet.yml, apps/nt-headless-ui/package.json, apps/nt-stylesheet/docs/README.md, apps/nt-stylesheet/docs/button.md, package.json
Summary #
- restructure nt-style and add publish script
=> feat: restructure nt-style and add publish script

.github/workflows/publish-and-release-reusable.yml
Summary #
- Modify the release flow so that a pull request is created to update the version after the release process
-   ✅ The code is linted with ESLint
-   ✅ The code is formatted with Prettier
-   ✅ All the tests have passed
-   ✅ The dependencies in `package.json` are correct and necessary (no unused or missing package)
-   ✅ Documentation has been added or updated
=> feat: fix pkg release

.github/workflows/publish-and-release-reusable.yml
Summary #
- Add permission release workflow
=> feat: update add-permission-release-workflow

package.json, pnpm-lock.yaml
=> feat: fix security

apps/nt-headless-ui/components/ui/multi-select/hooks/use-multi-select.spec.ts, apps/nt-headless-ui/components/ui/multi-select/hooks/use-multi-select.ts, apps/nt-headless-ui/components/ui/multi-select/multi-select.spec.tsx, apps/nt-headless-ui/components/ui/multi-select/multi-select.tsx, apps/nt-stylesheet/src/styles/components/_nt-multiselect.scss
Summary #
- Add multiple select 
=> feat: add multi select component

apps/nt-stylesheet/examples/modal.html, apps/nt-stylesheet/src/scripts/nt-modal.spec.ts, apps/nt-stylesheet/src/scripts/nt-modal.ts, apps/nt-stylesheet/src/styles/components/_nt-modal.scss
Summary #
- Fix modal example
**Before**
**After**
=> feat: fix modal example

apps/nt-stylesheet/examples/example.js, apps/nt-stylesheet/index.html, apps/nt-stylesheet/src/branding/nashtech/_index.scss, apps/nt-stylesheet/src/styles/_variables.scss, apps/nt-stylesheet/src/styles/layouts/_side-menu.scss, apps/nt-stylesheet/src/styles/layouts/nt-layout.scss, package.json, pnpm-lock.yaml
Summary #
- Update example menu slide bar
- Toggle in mobile and desktop
- Update audit
-   ✅  The code is linted with ESLint
-   ✅  The code is formatted with Prettier
-   ✅  All the tests have passed
-   ✅  The dependencies in `package.json` are correct and necessary (no unused or missing package)
-   ✅  Documentation has been added or updated
=> Feat: slide bars mobile example

apps/nt-headless-ui/package.json, pnpm-lock.yaml
Summary #
-   ✅ The code is linted with ESLint
-   ✅ The code is formatted with Prettier
-   ✅ All the tests have passed
-   ✅ The dependencies in `package.json` are correct and necessary (no unused or missing package)
-   ✅ Documentation has been added or updated
=> feat: fix audit

apps/nt-stylesheet/src/styles/_typography.scss, apps/nt-stylesheet/src/styles/components/_nt-alert.scss, apps/nt-stylesheet/src/styles/components/_nt-breadcrumb.scss, apps/nt-stylesheet/src/styles/components/_nt-input.scss, apps/nt-stylesheet/src/styles/layouts/nt-layout.scss
Summary #
- fix build error warning
-   ✅ The code is linted with ESLint
-   ✅ The code is formatted with Prettier
-   ✅ All the tests have passed
-   ✅ The dependencies in `package.json` are correct and necessary (no unused or missing package)
-   ✅ Documentation has been added or updated
=> feat: fix build error warning
